### ISSUE TITLE
Not able to login, when added as remote for a workspace

### ISSUE THREAD

**Issue by HenriPodolski** [teambit/bit-docker#1]
Hi,
whenever I try to add the remote to the docker container via `bit remote add ssh://root@<hostname>:22:/tmp/scope` it asks for username and password, even if ssh key is loaded by host system. Unfortunately it is not clear where those credentials needs to be provided. It does not seem like those are provided by the ssh key copied to the container. 

Can you please provide in the documentation how this can be solved?

**Comment by LeonYanghaha** [comment]
I'm also confused about this. How did you solve it?

**Comment by LeonYanghaha** [comment]
I'm also confused about this. How did you solve it? @HenriPodolski

**Comment by HenriPodolski** [comment]
No solution yet. I was evaluating bit and I am still waiting for a reply.

**Comment by cbaddeley** [comment]
I think you're using the wrong port. 22 is what the container is using. Type 'docker container ls' and you should see your bit-docker container running, and under PORTS for mine it shows 0.0.0.0:12345->22/tcp. That 12345 is what you want to use in your bit remote command.

bit remote add ssh://root@localhost:12345:/tmp/scope -g

**Comment by LeonYanghaha** [comment]
This should not be my case. I specified the port through ``` - p 8888:22``` when I started. I still need to enter the user name and password to use port 8888. @cbaddeley

**Comment by LeonYanghaha** [comment]
My situation is: when I start the first docker container, everything is OK.. But when I start the second one, I need to enter the user name and password. I don't know what password I should enter, physical machine or docker container? I'm confused why?



Why do I start more than one bit serve? Because I want to implement permission management on the bit, my idea is: start more than one serve, and mount different directories of the host to different docker containers to realize different users to operate different bit serve. If you have a better way, please let me know. Thank you

**Comment by dehuiZhang** [comment]
i also happen this problem， how i can solve it？

**Comment by dehuiZhang** [comment]
@LeonYanghaha  do you solve bit-docker ？

**Comment by LeonYanghaha** [comment]
check folder permissions, check network availability, check SSH service，When all this is OK, your bit server should be ok @dehuiZhang

**Comment by elevensky** [comment]
so am i.

**Comment by dehuiZhang** [comment]
> check folder permissions, check network availability, check SSH service，When all this is OK, your bit server should be ok @dehuiZhang
@LeonYanghaha  @cbaddeley 
when bit remote add , need username and password 
![image](https://user-images.githubusercontent.com/21165726/82330219-1f662500-9a15-11ea-8165-0beeeeb332ee.png)

**Comment by elevensky** [comment]
@dehuiZhang 
docker 共享了你本地的ssh文件，你看看你本地有 id_rsa.pub不。
我这重新生成了个，重起了个container就好了

**Comment by dehuiZhang** [comment]
> @dehuiZhang
> docker 共享了你本地的ssh文件，你看看你本地有 id_rsa.pub不。
> 我这重新生成了个，重起了个container就好了

@elevensky  我本地~/.ssh/id_rsa.pub 是有的  重启container还是 bit remote add 失败
![image](https://user-images.githubusercontent.com/21165726/82409707-e2e00b00-9aa0-11ea-8d3f-b9814c59ad81.png)
![image](https://user-images.githubusercontent.com/21165726/82409753-f4291780-9aa0-11ea-8418-e0cf7a95cbb0.png)
![image](https://user-images.githubusercontent.com/21165726/82411839-1e7cd400-9aa5-11ea-853d-7cb44c215996.png)
![image](https://user-images.githubusercontent.com/21165726/82409803-1327a980-9aa1-11ea-87c1-3535ee923a62.png)

**Comment by LeonYanghaha** [comment]
注意看container里的~/.ssh/id_rsa.pub的权限。

**Comment by LeonYanghaha** [comment]
@dehuiZhang 注意看container里的~/.ssh/id_rsa.pub的权限。

**Comment by dehuiZhang** [comment]
> @dehuiZhang 注意看container里的~/.ssh/id_rsa.pub的权限。

@LeonYanghaha  什么意思？

**Comment by LeonYanghaha** [comment]
@dehuiZhang [这里](https://blog.csdn.net/qq_27084325/article/details/98604589)

**Comment by dehuiZhang** [comment]
> @dehuiZhang [这里](https://blog.csdn.net/qq_27084325/article/details/98604589)

@LeonYanghaha 
![image](https://user-images.githubusercontent.com/21165726/82466032-80175f80-9af2-11ea-977f-00182b81540b.png)
我可以ssh 无需密码连接成功  但是bit remote add 失败

**Comment by elevensky** [comment]
@GiladShoham can help?

**Comment by dehuiZhang** [comment]
![image](https://user-images.githubusercontent.com/21165726/82812468-a445b880-9ec5-11ea-8b87-57692f094e3c.png)
权限是正确的 依旧不能bit remote add 成功 @LeonYanghaha

**Comment by elevensky** [comment]
@dehuiZhang 
after run
`eval "$(ssh-agent -s)"`
`ssh-add -K ~/.ssh/id_rsa`

here https://docs.bit.dev/docs/setup-authentication#authentication-issues

![image](https://user-images.githubusercontent.com/6904834/82817464-a1e85c00-9ecf-11ea-8217-2577c17d6935.png)
![image](https://user-images.githubusercontent.com/6904834/83003850-77b6ab80-a041-11ea-8bbf-17d97eb02592.png)

**Comment by dehuiZhang** [comment]
![image](https://user-images.githubusercontent.com/21165726/82997117-8a78b280-a038-11ea-8e4e-ed1e053f4a2d.png)
don't work  @elevensky

**Comment by dehuiZhang** [comment]
> @dehuiZhang
> after run
> `eval "$(ssh-agent -s)"`
> `ssh-add -K ~/.ssh/id_rsa`
> 
> here https://docs.bit.dev/docs/setup-authentication#authentication-issues
> 
> ![image](https://user-images.githubusercontent.com/6904834/82817464-a1e85c00-9ecf-11ea-8217-2577c17d6935.png)
> ![image](https://user-images.githubusercontent.com/6904834/83003850-77b6ab80-a041-11ea-8bbf-17d97eb02592.png)

after ` ssh-add -K ~/.ssh/id_rsa` it works  thanks! @elevensky

**Comment by GiladShoham** [comment]
@dehuiZhang @elevensky  sorry for the long reply.
Seems like the issue has been solved. can we close this?

**Comment by dehuiZhang** [comment]
> @dehuiZhang @elevensky sorry for the long reply.
> Seems like the issue has been solved. can we close this?

ok solved

**Comment by sLemaitre** [comment]
Here are my 2 cents on this topic:


Difference between **ssh into the container** vs ssh **key used by `add remote`** to the client.

To be able to ssh into the container is no test to see if bit can/will use given key key correctly.

### **IF** you wish to ssh into the container:
Following approach can be taken in order to not expose your key(s) inside the container which you might use in your network and is available for others. 
This approach can also be used to keep manual key-management to a minimum by linking the hots key-management with the container.

1. create or use a public key (ex. ~/.ssh/bit_rsa.pub)
2. only if you want to manually manage the authorized_keys between host en container:
`> mkdir ~/.ssh/bit-container`
`> touch authorized_keys`
2. copy your public key into your the authorized_keys of your host (or copy/rename the pub key)
`> cat ~/.ssh/bit_rsa.pub >> ~/.ssh/bit-container/authorized_keys`
3. mount the authorized_keys into the container on docker run:
`> --volume ~/.ssh/bit/authorized_keys:/root/.ssh/authorized_keys`
`> docker run --rm  --name bit  -d  -P  --volume ~/.ssh/bit-container/authorized_keys:/root/.ssh/authorized_keys bitcli/bit-
docker`
4. now you can ssh into the container:
Check the ip & port via `docker ps`
`> ssh root@{{ip}} -p {{port}} -i ~/.ssh/bit_rsa.pub`

However, I can't get Bit to use this key for use in the `bit remote add ssh://root@{{ip}}:{{port}}:/tmp/scope -g`

### What key does work for bit remote add

What did work for me was a key with the following restrictions:

1.  the key used must be exposed inside the container at /tmp/
2. the key must be named id_rsa.pub
3. the key may not have a passphrase
4. the key should have a specific size -b 4096
5. the key may not have a -C flag
6. you should always set appropriate rights to the key's
Ex.:
```
> ssh-keygen -t rsa -b 4096
> chmod 600 id_rsa
> chmod 644 id_rsa.pub
```
To attach this key to the container, use the documented statement:
`>  --volume ~/.ssh/bit/id_rsa.pub:/tmp/id_rsa.pub`

`> docker run --rm --name bit -d -P --volume ~/.ssh/bit/id_rsa.pub:/tmp/id_rsa.pub` bitcli/bit-
docker`

Note:
- one should prefer using --mount in stead of --volume
- you can add multiple mounts/volumes
Ex. combine the statements above into:
`> docker run --rm  --name bit  -d  -P --volume ~/.ssh/bit-countainer/authorized_keys:/root/.ssh/authorized_keys --volume ~/.ssh/bit/id_rsa.pub:/tmp/id_rsa.pub bitcli/bit-docker`

### I found it now to be possible to add the remote:
`> bit remote add ssh://root@{{ip}}:{{port}}:/tmp/scope -g`

### What still puzzles me:

As the key resides outside the container, a copy of the container will not contain the key. 
Howerver by exposing the key into the container via this way, any developer connecting to the container must have the same id_rsa as this is wat is registered upon spinning the container.
I did not succeed into adding multiple key's into the /tmp/ in the container.

_Resulting into all developers connecting to the container having to use the same key in order to publish to bit container?_

**Comment by marmxlab** [comment]
Thanks to the above comments. I finally got it working!

What you need to do are to make sure your ssh key is added to the ssh-agent and add it if it has not been added.

For example, if you are running the command from the instruction
```
docker run --rm --name bit -d -P  --volume ~/.ssh/id_rsa.pub:/tmp/id_rsa.pub bitcli/bit-docker
```
The key used here is `~/.ssh/id_rsa.pub`. Change it in the following steps accordingly if you are using a different key.


To check if it has already been added to the ssh-agent:

1. Calculate the fingerprint of your key
````
ssh-keygen -lf ~/.ssh/id_rsa.pub
````

2. See what keys are added to the ssh-agent
````
ssh-add -l
````
If you don't see your fingerprint listed there, that means your key has not been added to the ssh-agent yet and you should run the following:

3. Add your key to the ssh-agent
````
ssh-add ~/.ssh/bit/id_rsa
````

That's it! It should work now if you run the `bit remote add` command again.

**Comment by kevinPFish** [comment]
> @dehuiZhang
> after run
> `eval "$(ssh-agent -s)"`
> `ssh-add -K ~/.ssh/id_rsa`
> 
> here https://docs.bit.dev/docs/setup-authentication#authentication-issues
> 
> ![image](https://user-images.githubusercontent.com/6904834/82817464-a1e85c00-9ecf-11ea-8217-2577c17d6935.png)
> ![image](https://user-images.githubusercontent.com/6904834/83003850-77b6ab80-a041-11ea-8bbf-17d97eb02592.png)

hey, following your suggestion, `bit remote add` worked, but using `bit remote` failed
![image](https://user-images.githubusercontent.com/24239616/113260578-03a00080-9301-11eb-9638-2ef9a42123e9.png)
